### PR TITLE
OS Windows updated

### PR DESCRIPTION
**Pull request by Chewbakka-Wakka**
First test, more items need adding and descriptions also need to be done still.

### CODE REVIEW

**Comment by Chewbakka-Wakka** [comment]
Also updated README, to correct few spelling typos, and slight changes to wording.

**Review by ghost — COMMENTED** [review]
Please have look on Service MySQL or IF-MIB template. I'm going to move all Changelog entries to README.md

**Review by ghost — APPROVED** [review]
Please have look on Service MySQL or IF-MIB template. I'm going to move all Changelog entries to README.md

**Comment by kloczek** [comment]
Merged but I need to review those changes one more time on my local copy of the repo.

About naming convention.
Adding 3-4 characters should be added definitely to the trigger names.
In case of the items this seems is redundant as in host->items view each item always always listed with template name and in Latest data view is listed under exact Application so now SYS::Uptime key is listed under SYS Application which seems duplicates this SYS.
In items list view it will be no problem with for example multiple items like Uptime when they will be listed as for example:
OS Linux: Uptime
Service MySQL: Uptime

Only thing which is missing is have similar view in Latest data detailed view. However I just located place in php code which needs to be modified to have template or LLD name in item name in Latest data view like it is in Items list view, I'm going to submit this change to zabbix main source tree.

Another thing is submitting changes. Please try to push changes in smaller chunks with even more pull requests. With less changes introduced in each step it will be easier to make decision about committing the change or not.

**Comment by Chewbakka-Wakka** [comment]
Ok, think I understand most of that. Should I continue to name items the
way I have been or do another way?

This is what I see in my Zabbix when I search host -> items

OS Windows <http://192.168.77.206/items.php?hostid=10265&filter_set=1>:
SYS::Uptime
<http://192.168.77.206/items.php?form=update&hostid=10261&itemid=28714>

Actually it should be 2-4 characters, to cover HW::

I do see what you mean about Latest data detailed view, so yes ok.

Ok, I will do this with making changes/pushing from now on.

For OS Windows first I am adding items, and then after create some trigger
conditions when I learn and observe more about what is happening on my
system.

On Windows template, these counters are possible to add. Should these be
under MEM or SYS? I'm thinking MEM as it is memory related primarily. (or
some of these)

\Memory\System Code Total Bytes
\Memory\System Code Resident Bytes
\Memory\System Driver Total Bytes
\Memory\System Driver Resident Bytes
\Memory\System Cache Resident Bytes

Also on OS Windows this item is always as value 1. Another on my todo list
- proc.num[]

**Pull request merged**
